apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-vprodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: aws-ebs  # Use the name of your StorageClass
